server:
  port:8090
spring:
  datasource:
    url:url=jdbc:mysql://localhost:3306/hometree?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name:com.sql.jdbc.Driver
    username=root
    password=123456

