server:
  port:8090
spring:
  datasource:
    url:url=jdbc:mysql://localhost:3306/hometree?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name:com.sql.jdbc.Driver
    username=root
    password=123456
